version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: secretsanta
      MYSQL_USER: admin
      MYSQL_PASSWORD: nimda
      MYSQL_ROOT_PASSWORD: NIMDA
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 4000:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: NIMDA
volumes:
  db_data:

